### ISSUE TITLE
Upgrade from 0.3.0 to 1.0.1 breaks due to controller method names policies

### ISSUE THREAD

**Issue by tirdadc** [elabs/pundit#329]
I have an existing Policy ActiveRecord model that represents a non-Pundit model, and my Company model has a `has_many policies` relationship to it. The Pundit policy was consequently named PolicyPolicy, and this setup was working fine in 0.3.0 but broke when I upgraded to 1.0.1:

```
NoMethodError - undefined method `[]' for nil:NilClass:
  pundit (1.0.1) lib/pundit.rb:137:in `policy'
  pundit (1.0.1) lib/pundit.rb:115:in `authorize'
  app/controllers/companies_controller.rb:10:in `index'
  ...
```
I can rename the model but I was wondering if there's any other way to prevent this issue.

EDIT: the offending line in the Companies controller:

```
authorize :company, :index?
```

and the related CompanyPolicy section:

```
class CompanyPolicy < ApplicationPolicy
  def index?
    user.admin?
  end
  ...
end
```
Every other model set up in an identical fashion seems to be working fine, not sure what the issue is with Company.

**Comment by tirdadc** [comment]
It turned out to have nothing to do with the existing model named Policy, but the fact that my CompaniesController had a method named `policies`. Renaming that to `company_policies` solved the issue.
